export enum SudokuPatterns {
    '4_regular' = '4_regular',
    '5_cross' = '5_cross',
    '6_brickwall' = '6_brickwall',
    '6_ladder' = '6_ladder',
    '7_diagonal' = '7_diagonal',
    '8_brickwall' = '8_brickwall',
    '8_ladder' = '8_ladder',
    '8_cross' = '8_cross',
    '9_regular' = '9_regular',
    '10_brickwall' = '10_brickwall',
    '10_ladder' = '10_ladder',
    '10_ladder_2' = '10_ladder_2',
    '10_diagonal' = '10_diagonal',
    '10_diamond' = '10_diamond',
    '12_brickwall' = '12_brickwall',
    '12_cross' = '12_cross',
    '12_ladder' = '12_ladder',
    '12_short_and_long' = '12_short_and_long',
    '16_regular' = '16_regular',
}
