on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v2

      - name: Setup node
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Generate changelog
        id: generate-changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'docs(changelog): ${{ github.ref_name }}'
          git-user-name: ${{ secrets.MAINTAINER_NAME }}
          git-user-email: ${{ secrets.MAINTAINER_EMAIL }}
          release-count: '0'
          skip-on-empty: 'false'
          skip-version-file: 'true'
          skip-tag: 'true'
          skip-ci: 'true'

      - name: Pulish to npm
        id: publish-to-npm
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm ci
          npm run build
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create github release
        id: create-github-release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ github.ref }}",
              body: "${{ steps.generate-changelog.outputs.clean_changelog }}"
            });
